# Generated by Django 3.2.6 on 2021-08-04 18:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('levelupapi', '0002_auto_20210804_1438'),
    ]

    operations = [
        migrations.RenameField(
            model_name='event',
            old_name='host',
            new_name='organizer',
        ),
    ]
